### ISSUE TITLE
/releases?ftime=null throws internal server error

### ISSUE THREAD

**Issue by hskwirblies** [eBayClassifiedsGroup/orlo#37]
---

DEBUG in queries [/root/orlo/orlo/queries.py:145]:
## Filtering: Release.ftime == null

[2016-06-17 05:29:38 +0000] [3303] [ERROR] Error handling request /releases?ftime=null
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.6.0-py2.7.egg/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/wsgi.py", line 703, in **next**
    return self._next()
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.11.10-py2.7.egg/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
  File "/root/orlo/orlo/util.py", line 161, in stream_json_list
    iterator = iterator.__iter__()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2761, in **iter**
    return self._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, _args)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 600, in _init_compiled
    for key in compiled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 600, in <genexpr>
    for key in compiled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/type_api.py", line 982, in process
    return process_param(value, dialect)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy_Utils-0.32.7-py2.7.egg/sqlalchemy_utils/types/arrow.py", line 69, in process_bind_param
    utc_val = self._coerce(value).to('UTC')
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy_Utils-0.32.7-py2.7.egg/sqlalchemy_utils/types/arrow.py", line 85, in _coerce
    value = arrow.get(value)
  File "/usr/local/lib/python2.7/dist-packages/arrow-0.8.0-py2.7.egg/arrow/api.py", line 23, in get
    return _factory.get(_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/arrow-0.8.0-py2.7.egg/arrow/factory.py", line 164, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/usr/local/lib/python2.7/dist-packages/arrow-0.8.0-py2.7.egg/arrow/parser.py", line 119, in parse_iso
    return self._parse_multiformat(string, formats)
  File "/usr/local/lib/python2.7/dist-packages/arrow-0.8.0-py2.7.egg/arrow/parser.py", line 270, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
StatementError: (arrow.parser.ParserError) Could not match input to any of [u'YYYY-MM-DD', u'YYYY/MM/DD', u'YYYY.MM.DD', u'YYYY-MM', u'YYYY/MM', u'YYYY.MM', u'YYYY', u'YYYY', u'YYYY'] on 'null' [SQL: u'SELECT release.id AS release_id, release."references" AS release_references, release.stime AS release_stime, release.ftime AS release_ftime, release.duration AS release_duration, release."user" AS release_user, release.team AS release_team \nFROM release \nWHERE release.ftime = %(ftime_1)s ORDER BY release.stime ASC'] [parameters: [immutabledict({})]]

**Comment by al4** [comment]
Thanks for the report, will fix this ASAP
